seo_admin:
  resource: "@PNMediaBundle/Controller/Administration"
  type: annotation
  prefix: /admin/media

download:
  path: /download
  defaults: { _controller: PN\MediaBundle\Controller\DownloadController::download }