seo_admin:
    resource: "@PNMediaBundle/Controller/Administration"
    type:     annotation
    prefix:   /admin/media
    
download:
    path:   /download
    defaults:  { _controller: PNMediaBundle:Download:Download }