services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  pn_media_upload_image:
    class: PN\MediaBundle\Service\UploadImageService
  pn_media_upload_document:
    class: PN\MediaBundle\Service\UploadDocumentService

  PN\MediaBundle\Service\:
    resource: '../../Service/*'

  PN\MediaBundle\Twig\:
    public: false
    resource: '../../Twig/*'

  PN\MediaBundle\Controller\:
    public: false
    resource: '../../Controller/*'
    tags: [ 'controller.service_arguments' ]

  PN\MediaBundle\Controller\Administration\:
    public: false
    resource: '../../Controller/Administration/*'
    tags: [ 'controller.service_arguments' ]

  PN\MediaBundle\Repository\:
    resource: '../../Repository/*'
    tags: [ 'doctrine.repository_service' ]
