<?php

namespace PN\MediaBundle\Repository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;
use PN\MediaBundle\Entity\ImageSetting;
use PN\ServiceBundle\Utils\SQL;
use PN\ServiceBundle\Utils\Validate;

/**
 * ImageSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageSettingRepository extends ServiceEntityRepository
{

    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, ImageSetting::class);
    }

    public function findByEntity($entity)
    {
        $entityName = $entity;
        if (is_object($entity)) {
            $entityName = (new \ReflectionClass($entity))->getShortName();
        }
        $imageSetting = $this->findOneByEntityName($entityName);

        if (!$imageSetting) {
            throw new \Exception("Can't find ImageSetting");
        }

        return $imageSetting;
    }

    public function filter($search, $count = false, $startLimit = null, $endLimit = null)
    {

        $sortSQL = [
            0 => 's.entity_name',
        ];
        $connection = $this->getEntityManager()->getConnection();
        $where = false;
        $clause = '';

        $searchFiltered = new \stdClass();
        foreach ($search as $key => $value) {
            if (Validate::not_null($value) and !is_array($value)) {
                $searchFiltered->{$key} = substr($connection->quote($value), 1, -1);
            } else {
                $searchFiltered->{$key} = $value;
            }
        }


        if (isset($searchFiltered->string) and $searchFiltered->string) {

            if (SQL::validateSS($searchFiltered->string)) {
                $where = ($where) ? ' AND ( ' : ' WHERE ( ';
                $clause .= SQL::searchSCG($searchFiltered->string, 's.id', $where);
                $clause .= SQL::searchSCG($searchFiltered->string, 's.entity_name', ' OR ');
                $clause .= " ) ";
            }
        }

        if ($count) {
            $sqlInner = "SELECT count(s.id) as `count` FROM image_setting s ";

            $statement = $connection->prepare($sqlInner);

            return $statement->executeQuery()->fetchOne();
        }

        $sql = "SELECT s.id FROM image_setting s";
        $sql .= $clause;

        if (isset($searchFiltered->ordr) and Validate::not_null($searchFiltered->ordr)) {
            $dir = $searchFiltered->ordr['dir'];
            $columnNumber = $searchFiltered->ordr['column'];
            if (isset($columnNumber) and array_key_exists($columnNumber, $sortSQL)) {
                $sql .= " ORDER BY ".$sortSQL[$columnNumber]." $dir";
            }
        } else {
            $sql .= ' ORDER BY s.id DESC';
        }


        if ($startLimit !== null and $endLimit !== null) {
            $sql .= " LIMIT ".$startLimit.", ".$endLimit;
        }

        $statement = $connection->prepare($sql);
        $filterResult = $statement->executeQuery()->fetchAllAssociative();
        $result = $ids = [];
        foreach ($filterResult as $key => $r) {
            $ids[] = $r['id'];
        }

        if (count($ids) > 0) {
            $result = $this->findBy(["id" => $ids]);
        }

        return $result;
    }

}
