<?php

namespace PN\MediaBundle\Repository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;
use PN\MediaBundle\Entity\ImageSettingHasType;
use PN\ServiceBundle\Utils\SQL;
use PN\ServiceBundle\Utils\Validate;

/**
 * ImageSettingHasTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageSettingHasTypeRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, ImageSettingHasType::class);
    }

    public function filter($search, $count = false, $startLimit = null, $endLimit = null)
    {

        $sortSQL = [
            0 => 'it.name',
            1 => 'ist.radio_button',
            2 => 'ist.width',
            3 => 'ist.thumb_width',
        ];
        $connection = $this->getEntityManager()->getConnection();
        $where = false;
        $clause = '';

        $searchFiltered = new \stdClass();
        foreach ($search as $key => $value) {
            if (Validate::not_null($value) and !is_array($value)) {
                $searchFiltered->{$key} = substr($connection->quote($value), 1, -1);
            } else {
                $searchFiltered->{$key} = $value;
            }
        }

        if (isset($searchFiltered->imageSetting) and Validate::not_null($searchFiltered->imageSetting)) {
            $where = ($where) ? " AND " : " WHERE ";
            $clause .= $where." ist.image_setting_id = $searchFiltered->imageSetting ";
        }

        if (isset($searchFiltered->string) and $searchFiltered->string) {

            if (SQL::validateSS($searchFiltered->string)) {
                $where = ($where) ? ' AND ( ' : ' WHERE ( ';
                $clause .= SQL::searchSCG($searchFiltered->string, 'it.name', $where);
                $clause .= " ) ";
            }
        }

        if ($count) {
            $sqlInner = "SELECT count(*) as `count` FROM image_setting_has_type ist "
                ." LEFT OUTER JOIN image_type it ON ist.image_type_id=it.id ";

            $statement = $connection->prepare($sqlInner);

            return $statement->executeQuery()->fetchOne();

        }

        $sql = "SELECT ist.image_type_id as imageTypeId, ist.image_setting_id as imageSettingId FROM image_setting_has_type ist "
            ." LEFT OUTER JOIN image_type it ON ist.image_type_id=it.id ";
        $sql .= $clause;

        if (isset($searchFiltered->ordr) and Validate::not_null($searchFiltered->ordr)) {
            $dir = $searchFiltered->ordr['dir'];
            $columnNumber = $searchFiltered->ordr['column'];
            if (isset($columnNumber) and array_key_exists($columnNumber, $sortSQL)) {
                $sql .= " ORDER BY ".$sortSQL[$columnNumber]." $dir";
            }
        }


        if ($startLimit !== null and $endLimit !== null) {
            $sql .= " LIMIT ".$startLimit.", ".$endLimit;
        }

        $statement = $connection->prepare($sql);
        $filterResult = $statement->executeQuery()->fetchAllAssociative();
        $result = array();

        foreach ($filterResult as $key => $r) {
            $result[] = $this->findOneBy(['imageType' => $r['imageTypeId'], 'imageSetting' => $r['imageSettingId']]);
        }

        return $result;
    }

}
